### ISSUE TITLE
Test with python 3.11

### ISSUE THREAD

**Issue by pgleeson** [ModECI/modelspec#25]
Under way here: https://github.com/ModECI/modelspec/tree/experimental

**Comment by pgleeson** [comment]
Issue is now: "ERROR: No matching distribution found for onnxruntime>=1.12.0". See also https://github.com/ModECI/MDF/issues/362

**Comment by parikshit14** [comment]
Support for python 3.11 will be added in next release of onnxruntime, mentioned in 
issue: https://github.com/microsoft/onnxruntime/issues/14880

**Comment by pgleeson** [comment]
Thanks @parikshit14! Not super urgent from our side, but good to know where the blocker is.

**Comment by sanjayankur31** [comment]
onnxruntime and onnx both support py3.11 now, so this is ready to go. See https://github.com/ModECI/MDF/pull/470 for MDF

**Comment by pgleeson** [comment]
Tested on development
